version: "3.4"
services:
  pg_tileserv:
    image: "pramsey/pg_tileserv:20231005"
    ports:
    - 8801:7800
    environment:
    - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
    # volumes:
    # - ./pg_tileserv.toml:/etc/pg_tileserv.toml
    restart: always
  pg_featureserv:
    image: "pramsey/pg_featureserv:latest"
    ports:
    - 9000:9000
    environment:
    # CHANGE connection string from .env file
    - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
    restart: always
  geoserver:
      image: geosolutionsit/geoserver
      ports:
      - 8080:8080
      environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS="PGRaster"
      volumes:
      - ./web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
      - ./Laboratoires/Lab7/geoserverData:/var/geoserver/datadir
      restart: always
  server-web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./app/:/usr/share/nginx/html
volumes:
  data:

  